pyrpl:
  background_color: ''
  dock_positions: "\0\0\0\xFF\0\0\0\0\xFD\0\0\0\x01\0\0\0\x02\0\0\x04\xCE\0\0\x02\
    /\xFC\x01\0\0\0\x01\xFC\0\0\0\0\0\0\x04\xCE\0\0\0y\0\xFF\xFF\xFF\xFA\0\0\0\x03\
    \x01\0\0\0\r\xFB\0\0\0$\0a\0s\0g\0s\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\x01\
    \0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\xFB\0\0\0\"\0i\0q\0s\0 \0(\0p\0\
    d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\
    \xFB\0\0\0$\0p\0i\0d\0s\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\0\0\0\0\0\xFF\
    \xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0(\0s\0c\0o\0p\0e\0s\0 \0(\0p\0d\0\
    h\0_\0e\0x\0a\0m\0p\0l\0e\0)\x01\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\xFB\
    \0\0\0$\0i\0i\0r\0s\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\0\0\0\0\0\xFF\xFF\
    \xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0&\0t\0r\0i\0g\0s\0 \0(\0p\0d\0h\0_\0\
    e\0x\0a\0m\0p\0l\0e\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\
    \0\0$\0p\0w\0m\0s\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\0\0\0\0\0\xFF\xFF\xFF\
    \xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0\"\0h\0k\0s\0 \0(\0p\0d\0h\0_\0e\0x\0a\0\
    m\0p\0l\0e\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0:\0n\0\
    e\0t\0w\0o\0r\0k\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0\
    e\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\0<\0s\0p\0e\0c\0\
    t\0r\0u\0m\0a\0n\0a\0l\0y\0z\0e\0r\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\0\
    \0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\02\0c\0u\0r\0v\0e\0v\0\
    i\0e\0w\0e\0r\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\
    \0\0\0\x16\0\xFF\xFF\xFF\xFB\0\0\02\0p\0y\0r\0p\0l\0c\0o\0n\0f\0i\0g\0 \0(\0p\0\
    d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\0\0\0\0\0\xFF\xFF\xFF\xFF\0\0\0\x16\0\xFF\xFF\xFF\
    \xFB\0\0\0*\0l\0o\0c\0k\0b\0o\0x\0 \0(\0p\0d\0h\0_\0e\0x\0a\0m\0p\0l\0e\0)\x01\
    \0\0\0\0\xFF\xFF\xFF\xFF\0\0\0]\0\xFF\xFF\xFF\0\0\x04\xCE\0\0\0\0\0\0\0\x04\0\0\
    \0\x04\0\0\0\b\0\0\0\b\xFC\0\0\0\0"
  loglevel: info
  modules:
  - NetworkAnalyzer
  - SpectrumAnalyzer
  - CurveViewer
  - PyrplConfig
  - Lockbox
  name: pdh_example
  window_position:
  - 236
  - 81
  - 1230
  - 600
redpitaya:
  autostart: true
  delay: 0.05
  frequency_correction: 1.0
  gui: true
  hostname: 10.214.1.32
  leds_off: true
  monitor_server_name: monitor_server
  password: root
  port: 2222
  reloadfpga: true
  reloadserver: false
  serverbinfilename: fpga.bin
  serverdirname: //opt//pyrpl//
  silence_env: false
  sshport: 22
  timeout: 1
  user: root
scope:
  curve_name: scope curve
  duration: 0.004194304
  input1: in1
  input2: iq0
  rolling_mode: false
  run_continuous: false
  threshold: 0.800048828125
  trigger_source: asg0
  trace_average: 1
  average: false
  trigger_delay: 0.6655
  hysteresis: 0.00244140625
  ch1_active: true
  ch2_active: true
  ch_math_active: false
  math_formula: ch1 * ch2
  xy_mode: false
pwm0:
  input: 'off'
pwm1:
  input: 'off'
networkanalyzer:
  curve_name: networkanalyzer curve
spectrumanalyzer:
  curve_name: spectrumanalyzer curve
lockbox:
  sequence:
  - outputs: {}
  outputs:
    output1:
      assisted_design: true
      i: 100.0
      p: 0.0
      sweep_frequency: 10.0
iq0:
  acbandwidth: 77864.55296535754
  amplitude: 0.9999923706054688
  bandwidth:
  - 3108131.4996426
  - 3108131.4996426
  frequency: 49999999.98835847
  input: in1
  output_direct: out2
  phase: 125.00000000931323
  quadrature_factor: 30.0
asg0:
  amplitude: 1.0
  frequency: 5.005858838558197
  offset: 0.0
  output_direct: out1
  trigger_source: immediately
  waveform: ramp
iir:
  loops: 5
  'on': true
scope_states:
  autosweep:
    average: false
    ch1_active: true
    ch2_active: true
    ch_math_active: false
    curve_name: scope curve
    duration: 0.268435456
    hysteresis: 0.00244140625
    input1: in1
    input2: iq0
    math_formula: ch1 * ch2
    rolling_mode: false
    run_continuous: true
    threshold: 0.800048828125
    trace_average: 1
    trigger_delay: 0.6655
    trigger_source: asg0
    xy_mode: false
  autosweep_zoom:
    average: false
    ch1_active: true
    ch2_active: true
    ch_math_active: false
    curve_name: scope curve
    duration: 0.008388608
    hysteresis: 0.00244140625
    input1: in1
    input2: iq0
    math_formula: ch1 * ch2
    rolling_mode: false
    run_continuous: true
    threshold: 0.800048828125
    trace_average: 1
    trigger_delay: 0.6655
    trigger_source: ch1_negative_edge
    xy_mode: false
